name: grimp
channels:
  - defaults
dependencies:
  - pip
  - scikit-learn
  - scipy
  - setuptools
  - tqdm
  - numpy
  - pandas
  - gensim
  - seaborn
  - matplotlib
  - pip:
    - chardet==5.2.0
    - dgl==1.1.2.post1
    - fasttext==0.9.2
    - networkx==3.2.1
